import type { MapRoom, RoomId } from '@/types/agent';

export const MAP_ROOMS: MapRoom[] = [
  {
    id: 'jarvis',
    label: 'Meeting Hall',
    shortLabel: 'Meeting',
    description: 'Sala de reuniao para alinhamento entre todos os agentes.',
    theme: 'shared',
    x: 2,
    y: 3,
    w: 39,
    h: 31,
    agentX: 50,
    agentY: 56,
  },
  {
    id: 'claw',
    label: 'Dev + QA Forge',
    shortLabel: 'Dev/QA',
    description: 'Tomás implementa e Cecilia valida o trabalho no mesmo fluxo.',
    theme: 'dev',
    x: 59,
    y: 3,
    w: 39,
    h: 31,
    agentX: 50,
    agentY: 56,
  },
  {
    id: 'sentinel',
    label: 'Command Watch',
    shortLabel: 'Lilith',
    description: 'Lilith coordena prioridade, contexto e operacao.',
    theme: 'command',
    x: 2,
    y: 38,
    w: 37,
    h: 24,
    agentX: 54,
    agentY: 54,
  },
  {
    id: 'pixel',
    label: 'Market Studio',
    shortLabel: 'Market',
    description: 'Maya transforma estrategia em conteudo e copy.',
    theme: 'market',
    x: 61,
    y: 38,
    w: 37,
    h: 26,
    agentX: 50,
    agentY: 54,
  },
  {
    id: 'atlas',
    label: 'Treasury',
    shortLabel: 'Finance',
    description: 'Daikokuten organiza contas, dividas e prioridades financeiras.',
    theme: 'finance',
    x: 2,
    y: 67,
    w: 38,
    h: 29,
    agentX: 54,
    agentY: 52,
  },
  {
    id: 'conference',
    label: 'Platform Ops',
    shortLabel: 'Ops',
    description: 'Ariel cuida de gateway, runtime, integracoes e confiabilidade.',
    theme: 'ops',
    x: 60,
    y: 68,
    w: 38,
    h: 28,
    agentX: 50,
    agentY: 50,
  },
  {
    id: 'kitchen',
    label: 'Shared Lounge',
    shortLabel: 'Shared',
    description: 'Espaco de fallback para agentes sem sala dedicada.',
    theme: 'shared',
    x: 42,
    y: 36,
    w: 17,
    h: 60,
    agentX: 50,
    agentY: 58,
  },
];

export const MEETING_ROOM_ID: RoomId = 'jarvis';

export const AGENT_ROOM_MAP: Record<string, RoomId> = {
  main: 'sentinel',
  'clareza-dev': 'claw',
  'clareza-qa': 'claw',
  'nodesync-marketing': 'pixel',
  'personal-finance': 'atlas',
  'ariel-platform': 'conference',
};

export function roomForAgent(agentId: string): RoomId {
  return AGENT_ROOM_MAP[agentId] || 'kitchen';
}
