import type { MapRoom, RoomId } from '@/types/agent';

export const MAP_ROOMS: MapRoom[] = [
  {
    id: 'jarvis',
    label: 'Command Hall',
    shortLabel: 'Command',
    description: 'Lilith coordena prioridade, contexto e operacao.',
    theme: 'command',
    x: 4,
    y: 5,
    w: 39,
    h: 32,
    agentX: 58,
    agentY: 62,
  },
  {
    id: 'claw',
    label: 'Dev Forge',
    shortLabel: 'Dev',
    description: 'Tomás trabalha arquitetura, codigo e manutencao tecnica.',
    theme: 'dev',
    x: 4,
    y: 70,
    w: 35,
    h: 24,
    agentX: 58,
    agentY: 54,
  },
  {
    id: 'sentinel',
    label: 'QA Watchtower',
    shortLabel: 'QA',
    description: 'Cecilia valida risco, regressao e decisao de release.',
    theme: 'qa',
    x: 4,
    y: 43,
    w: 35,
    h: 21,
    agentX: 58,
    agentY: 56,
  },
  {
    id: 'pixel',
    label: 'Market Studio',
    shortLabel: 'Market',
    description: 'Maya transforma estrategia em conteudo e copy.',
    theme: 'market',
    x: 60,
    y: 43,
    w: 35,
    h: 24,
    agentX: 52,
    agentY: 54,
  },
  {
    id: 'atlas',
    label: 'Treasury',
    shortLabel: 'Finance',
    description: 'Daikokuten organiza contas, dividas e prioridades financeiras.',
    theme: 'finance',
    x: 59,
    y: 5,
    w: 36,
    h: 31,
    agentX: 51,
    agentY: 58,
  },
  {
    id: 'conference',
    label: 'Platform Ops',
    shortLabel: 'Ops',
    description: 'Ariel cuida de gateway, runtime, integracoes e confiabilidade.',
    theme: 'ops',
    x: 60,
    y: 72,
    w: 35,
    h: 22,
    agentX: 50,
    agentY: 48,
  },
  {
    id: 'kitchen',
    label: 'Shared Lounge',
    shortLabel: 'Shared',
    description: 'Espaco de fallback para agentes sem sala dedicada.',
    theme: 'shared',
    x: 42,
    y: 58,
    w: 15,
    h: 25,
    agentX: 50,
    agentY: 58,
  },
];

export const AGENT_ROOM_MAP: Record<string, RoomId> = {
  main: 'jarvis',
  'clareza-dev': 'claw',
  'clareza-qa': 'sentinel',
  'nodesync-marketing': 'pixel',
  'personal-finance': 'atlas',
  'ariel-platform': 'conference',
};

export function roomForAgent(agentId: string): RoomId {
  return AGENT_ROOM_MAP[agentId] || 'kitchen';
}
